// The languages a second subtitle can be in, shared by the popup and the
// welcome page so the two pickers can never offer different lists.

// The short list shown first: the languages most people here translate into.
globalThis.YDS_COMMON_LANGS = [
  ["zh-Hans", "中文（简体）"],
  ["zh-Hant", "中文（繁體）"],
  ["en", "English"],
  ["ja", "日本語"],
  ["ko", "한국어"],
  ["vi", "Tiếng Việt"],
  ["es", "Español"],
  ["pt", "Português"],
  ["fr", "Français"],
  ["de", "Deutsch"],
  ["ru", "Русский"],
  ["id", "Bahasa Indonesia"]
];

// Google Translate supported languages. Local name + English name for
// recognition. Codes are the ones Google Translate accepts (a few — zh-Hans,
// zh-Hant, iw, jw — are remapped in content.js's toGoogleLang).
globalThis.YDS_ALL_LANGS = [
  ["af", "Afrikaans"],
  ["sq", "Shqip · Albanian"],
  ["am", "አማርኛ · Amharic"],
  ["ar", "العربية · Arabic"],
  ["hy", "Հայերեն · Armenian"],
  ["as", "অসমীয়া · Assamese"],
  ["ay", "Aymar · Aymara"],
  ["az", "Azərbaycan · Azerbaijani"],
  ["bm", "Bamanankan · Bambara"],
  ["eu", "Euskara · Basque"],
  ["be", "Беларуская · Belarusian"],
  ["bn", "বাংলা · Bengali"],
  ["bho", "भोजपुरी · Bhojpuri"],
  ["bs", "Bosanski · Bosnian"],
  ["bg", "Български · Bulgarian"],
  ["ca", "Català · Catalan"],
  ["ceb", "Cebuano"],
  ["ny", "Chichewa"],
  ["co", "Corsu · Corsican"],
  ["hr", "Hrvatski · Croatian"],
  ["cs", "Čeština · Czech"],
  ["da", "Dansk · Danish"],
  ["dv", "ދިވެހި · Dhivehi"],
  ["doi", "डोगरी · Dogri"],
  ["nl", "Nederlands · Dutch"],
  ["eo", "Esperanto"],
  ["et", "Eesti · Estonian"],
  ["ee", "Eʋegbe · Ewe"],
  ["fil", "Filipino / Tagalog"],
  ["fi", "Suomi · Finnish"],
  ["fy", "Frysk · Frisian"],
  ["gl", "Galego · Galician"],
  ["ka", "ქართული · Georgian"],
  ["el", "Ελληνικά · Greek"],
  ["gn", "Avañe'ẽ · Guarani"],
  ["gu", "ગુજરાતી · Gujarati"],
  ["ht", "Kreyòl · Haitian Creole"],
  ["ha", "Hausa"],
  ["haw", "ʻŌlelo Hawaiʻi · Hawaiian"],
  ["he", "עברית · Hebrew"],
  ["hi", "हिन्दी · Hindi"],
  ["hmn", "Hmoob · Hmong"],
  ["hu", "Magyar · Hungarian"],
  ["is", "Íslenska · Icelandic"],
  ["ig", "Igbo"],
  ["ilo", "Ilokano · Ilocano"],
  ["id", "Bahasa Indonesia · Indonesian"],
  ["ga", "Gaeilge · Irish"],
  ["it", "Italiano · Italian"],
  ["jv", "Basa Jawa · Javanese"],
  ["kn", "ಕನ್ನಡ · Kannada"],
  ["kk", "Қазақша · Kazakh"],
  ["km", "ខ្មែរ · Khmer"],
  ["rw", "Kinyarwanda"],
  ["gom", "कोंकणी · Konkani"],
  ["kri", "Krio"],
  ["ku", "Kurdî · Kurdish (Kurmanji)"],
  ["ckb", "کوردی · Kurdish (Sorani)"],
  ["ky", "Кыргызча · Kyrgyz"],
  ["lo", "ລາວ · Lao"],
  ["la", "Latina · Latin"],
  ["lv", "Latviešu · Latvian"],
  ["ln", "Lingála · Lingala"],
  ["lt", "Lietuvių · Lithuanian"],
  ["lg", "Luganda"],
  ["lb", "Lëtzebuergesch · Luxembourgish"],
  ["mk", "Македонски · Macedonian"],
  ["mai", "मैथिली · Maithili"],
  ["mg", "Malagasy"],
  ["ms", "Bahasa Melayu · Malay"],
  ["ml", "മലയാളം · Malayalam"],
  ["mt", "Malti · Maltese"],
  ["mi", "Māori"],
  ["mr", "मराठी · Marathi"],
  ["mni-Mtei", "ꯃꯤꯇꯩ ꯂꯣꯟ · Meiteilon"],
  ["lus", "Mizo"],
  ["mn", "Монгол · Mongolian"],
  ["my", "မြန်မာ · Myanmar (Burmese)"],
  ["ne", "नेपाली · Nepali"],
  ["no", "Norsk · Norwegian"],
  ["or", "ଓଡ଼ିଆ · Odia (Oriya)"],
  ["om", "Afaan Oromoo · Oromo"],
  ["ps", "پښتو · Pashto"],
  ["fa", "فارسی · Persian"],
  ["pl", "Polski · Polish"],
  ["pt", "Português · Portuguese"],
  ["pa", "ਪੰਜਾਬੀ · Punjabi"],
  ["qu", "Runa Simi · Quechua"],
  ["ro", "Română · Romanian"],
  ["ru", "Русский · Russian"],
  ["sm", "Gagana Samoa · Samoan"],
  ["sa", "संस्कृतम् · Sanskrit"],
  ["gd", "Gàidhlig · Scots Gaelic"],
  ["nso", "Sepedi"],
  ["sr", "Српски · Serbian"],
  ["st", "Sesotho"],
  ["sn", "Shona"],
  ["sd", "سنڌي · Sindhi"],
  ["si", "සිංහල · Sinhala"],
  ["sk", "Slovenčina · Slovak"],
  ["sl", "Slovenščina · Slovenian"],
  ["so", "Soomaali · Somali"],
  ["su", "Basa Sunda · Sundanese"],
  ["sw", "Kiswahili · Swahili"],
  ["sv", "Svenska · Swedish"],
  ["tg", "Тоҷикӣ · Tajik"],
  ["ta", "தமிழ் · Tamil"],
  ["tt", "Татарча · Tatar"],
  ["te", "తెలుగు · Telugu"],
  ["th", "ไทย · Thai"],
  ["ti", "ትግርኛ · Tigrinya"],
  ["ts", "Xitsonga · Tsonga"],
  ["tr", "Türkçe · Turkish"],
  ["tk", "Türkmen · Turkmen"],
  ["ak", "Twi (Akan)"],
  ["uk", "Українська · Ukrainian"],
  ["ur", "اردو · Urdu"],
  ["ug", "ئۇيغۇرچە · Uyghur"],
  ["uz", "Oʻzbek · Uzbek"],
  ["vi", "Tiếng Việt · Vietnamese"],
  ["cy", "Cymraeg · Welsh"],
  ["xh", "isiXhosa · Xhosa"],
  ["yi", "ייִדיש · Yiddish"],
  ["yo", "Yorùbá · Yoruba"],
  ["zu", "isiZulu · Zulu"]
];
